version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: sports_science_db
    environment:
      POSTGRES_DB: sports_science
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sports_science_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sports_science"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: sports_science_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped



networks:
  default:
    name: sports_science_network